name: '🩺 No Cache'

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os:
                - ubuntu-latest
                - macos-latest
                - windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Uglified build
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build